{
"project_name" : "Elansol Technologies Assignment",
"author": "Prakash pacharne",
"mode" : "video",
"image_size" : 640,
"classes" : 0,
"persist" : "True",
"conf_threshold" : 0.2,
"resize_width" : 640,
"resize_height": 640,
"normalize_frames" : "True",
"log_file_path" : "C:\\Users\\ASUS\\OneDrive\\Desktop\\worker\\assets\\idle_detection.log",
"pretrained_model_pt_path" : "C:\\Users\\ASUS\\OneDrive\\Desktop\\worker\\assets\\yolov9t.pt",
"pretrained_model_onnx_path" : "C:\\Users\\ASUS\\OneDrive\\Desktop\\worker\\assets\\yolov9t.onnx",
"rtsp_link" : "rtsp://admin:admin123@192.168.1.111:554//Streaming//Channel//101",
"inference_video" : "C:\\Users\\ASUS\\OneDrive\\Desktop\\worker\\assets\\sleeping.webm",
"roi_points" : "C:\\Users\\ASUS\\OneDrive\\Desktop\\worker\\assets\\roi_points.txt",
"verbose_history" : 0,
"iou_threshold": 0.3,
"dis_lines" : "y",
"idle_alert_threshold" : 10,
"movement_threshold" : 2.5
}